version: '3.7'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - webapp
    volumes:
      - ./services/nginx/var/www:/var/www

  webapp:
    container_name: 'webapp'
    build: ./services/webapp-rust
    volumes:
      - uploaded_data:/app/data

volumes:
  uploaded_data:
